name: Expo CI (Modern)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  expo-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: npm ci

      - name: Run expo-doctor
        run: npx expo-doctor

      - name: Check TypeScript
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

      - name: Validate Expo configuration
        run: npx expo config --type introspect

      - name: Build check (Web)
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
        run: npx expo export --platform web --clear
