name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.19.4
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Show Node and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies (CI)
        run: npm ci

      - name: Run unit/integration tests
        run: npm run test:ci

      - name: Run performance tests (basic)
        run: npm run test:performance

      - name: Run performance tests (advanced)
        run: npm run test:performance:advanced

  expo-build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.19.4
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Install Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: npm ci

      - name: Run expo-doctor
        run: npx expo-doctor || true

      - name: Check TypeScript
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

      - name: Validate Expo configuration
        run: npx expo config --type introspect

      - name: Build check (Web)
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
        run: npx expo export --platform web --clear
